elastic:
  image: registry.cn-qingdao.aliyuncs.com/wwmxd/elasticsearcher
  volumes:
    - ./esdata:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
  command: elasticsearch
 
logstash:
  image: registry.cn-qingdao.aliyuncs.com/wwmxd/logstash
  ports:
    - "5044:5044"
  volumes:
    - ./logstash/conf.d:/etc/logstash/conf.d:ro
    - ./logstash/patterns:/etc/logstash/patterns:ro
  net: "host"
  command: logstash -f /etc/logstash/conf.d
kibana:
  image: registry.cn-qingdao.aliyuncs.com/wwmxd/kibana
  ports:
    - "5601:5601"
  net: "host"
  environment:
    - ELASTICSEARCH_URL=http://localhost:9200
  command: kibana
filebeat:
  image: willfarrell/filebeat
  volumes:
    - ./filebeat:/etc/filebeat:ro
    - /home/userService:/data/logs
  net: "host"